/**
 * @file mochi.h
 *
 * @brief This header file was generated by cantools version 40.7.1 Wed Jul 15 22:02:26 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef MOCHI_H
#define MOCHI_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define MOCHI_RR_ACCEL_FRAME_ID (0x102u)
#define MOCHI_RR_GYRO_FRAME_ID (0x103u)
#define MOCHI_RR_LINPOT_FRAME_ID (0x104u)
#define MOCHI_RL_ACCEL_FRAME_ID (0x202u)
#define MOCHI_RL_GYRO_FRAME_ID (0x203u)
#define MOCHI_RL_LINPOT_FRAME_ID (0x204u)
#define MOCHI_FR_ACCEL_FRAME_ID (0x302u)
#define MOCHI_FR_GYRO_FRAME_ID (0x303u)
#define MOCHI_FR_LINPOT_FRAME_ID (0x304u)
#define MOCHI_FL_ACCEL_FRAME_ID (0x402u)
#define MOCHI_FL_GYRO_FRAME_ID (0x403u)
#define MOCHI_FL_LINPOT_FRAME_ID (0x404u)
#define MOCHI_SPEEDOMETER_FRAME_ID (0x502u)
#define MOCHI_TACHOMETER_FRAME_ID (0x503u)

/* Frame lengths in bytes. */
#define MOCHI_RR_ACCEL_LENGTH (6u)
#define MOCHI_RR_GYRO_LENGTH (6u)
#define MOCHI_RR_LINPOT_LENGTH (2u)
#define MOCHI_RL_ACCEL_LENGTH (6u)
#define MOCHI_RL_GYRO_LENGTH (6u)
#define MOCHI_RL_LINPOT_LENGTH (2u)
#define MOCHI_FR_ACCEL_LENGTH (6u)
#define MOCHI_FR_GYRO_LENGTH (6u)
#define MOCHI_FR_LINPOT_LENGTH (2u)
#define MOCHI_FL_ACCEL_LENGTH (6u)
#define MOCHI_FL_GYRO_LENGTH (6u)
#define MOCHI_FL_LINPOT_LENGTH (2u)
#define MOCHI_SPEEDOMETER_LENGTH (2u)
#define MOCHI_TACHOMETER_LENGTH (2u)

/* Extended or standard frame types. */
#define MOCHI_RR_ACCEL_IS_EXTENDED (0)
#define MOCHI_RR_GYRO_IS_EXTENDED (0)
#define MOCHI_RR_LINPOT_IS_EXTENDED (0)
#define MOCHI_RL_ACCEL_IS_EXTENDED (0)
#define MOCHI_RL_GYRO_IS_EXTENDED (0)
#define MOCHI_RL_LINPOT_IS_EXTENDED (0)
#define MOCHI_FR_ACCEL_IS_EXTENDED (0)
#define MOCHI_FR_GYRO_IS_EXTENDED (0)
#define MOCHI_FR_LINPOT_IS_EXTENDED (0)
#define MOCHI_FL_ACCEL_IS_EXTENDED (0)
#define MOCHI_FL_GYRO_IS_EXTENDED (0)
#define MOCHI_FL_LINPOT_IS_EXTENDED (0)
#define MOCHI_SPEEDOMETER_IS_EXTENDED (0)
#define MOCHI_TACHOMETER_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/* Frame Names. */
#define MOCHI_RR_ACCEL_NAME "rr_accel"
#define MOCHI_RR_GYRO_NAME "rr_gyro"
#define MOCHI_RR_LINPOT_NAME "rr_linpot"
#define MOCHI_RL_ACCEL_NAME "rl_accel"
#define MOCHI_RL_GYRO_NAME "rl_gyro"
#define MOCHI_RL_LINPOT_NAME "rl_linpot"
#define MOCHI_FR_ACCEL_NAME "fr_accel"
#define MOCHI_FR_GYRO_NAME "fr_gyro"
#define MOCHI_FR_LINPOT_NAME "fr_linpot"
#define MOCHI_FL_ACCEL_NAME "fl_accel"
#define MOCHI_FL_GYRO_NAME "fl_gyro"
#define MOCHI_FL_LINPOT_NAME "fl_linpot"
#define MOCHI_SPEEDOMETER_NAME "speedometer"
#define MOCHI_TACHOMETER_NAME "tachometer"

/* Signal Names. */
#define MOCHI_RR_ACCEL_ACCEL_X_NAME "accel_x"
#define MOCHI_RR_ACCEL_ACCEL_Y_NAME "accel_y"
#define MOCHI_RR_ACCEL_ACCEL_Z_NAME "accel_z"
#define MOCHI_RR_GYRO_GYRO_X_NAME "gyro_x"
#define MOCHI_RR_GYRO_GYRO_Y_NAME "gyro_y"
#define MOCHI_RR_GYRO_GYRO_Z_NAME "gyro_z"
#define MOCHI_RR_LINPOT_TRAVEL_NAME "travel"
#define MOCHI_RL_ACCEL_ACCEL_X_NAME "accel_x"
#define MOCHI_RL_ACCEL_ACCEL_Y_NAME "accel_y"
#define MOCHI_RL_ACCEL_ACCEL_Z_NAME "accel_z"
#define MOCHI_RL_GYRO_GYRO_X_NAME "gyro_x"
#define MOCHI_RL_GYRO_GYRO_Y_NAME "gyro_y"
#define MOCHI_RL_GYRO_GYRO_Z_NAME "gyro_z"
#define MOCHI_RL_LINPOT_TRAVEL_NAME "travel"
#define MOCHI_FR_ACCEL_ACCEL_X_NAME "accel_x"
#define MOCHI_FR_ACCEL_ACCEL_Y_NAME "accel_y"
#define MOCHI_FR_ACCEL_ACCEL_Z_NAME "accel_z"
#define MOCHI_FR_GYRO_GYRO_X_NAME "gyro_x"
#define MOCHI_FR_GYRO_GYRO_Y_NAME "gyro_y"
#define MOCHI_FR_GYRO_GYRO_Z_NAME "gyro_z"
#define MOCHI_FR_LINPOT_TRAVEL_NAME "travel"
#define MOCHI_FL_ACCEL_ACCEL_X_NAME "accel_x"
#define MOCHI_FL_ACCEL_ACCEL_Y_NAME "accel_y"
#define MOCHI_FL_ACCEL_ACCEL_Z_NAME "accel_z"
#define MOCHI_FL_GYRO_GYRO_X_NAME "gyro_x"
#define MOCHI_FL_GYRO_GYRO_Y_NAME "gyro_y"
#define MOCHI_FL_GYRO_GYRO_Z_NAME "gyro_z"
#define MOCHI_FL_LINPOT_TRAVEL_NAME "travel"
#define MOCHI_SPEEDOMETER_SPEED_NAME "speed"
#define MOCHI_TACHOMETER_RPM_NAME "rpm"

/**
 * Signals in message rr_accel.
 *
 * All signal values are as on the CAN bus.
 */
struct mochi_rr_accel_t {
    /**
     * Range: -32768..32768 (-8..8 g)
     * Scale: 0.000244140625
     * Offset: 0
     */
    int16_t accel_x;

    /**
     * Range: -32768..32768 (-8..8 g)
     * Scale: 0.000244140625
     * Offset: 0
     */
    int16_t accel_y;

    /**
     * Range: -32768..32768 (-8..8 g)
     * Scale: 0.000244140625
     * Offset: 0
     */
    int16_t accel_z;
};

/**
 * Signals in message rr_gyro.
 *
 * All signal values are as on the CAN bus.
 */
struct mochi_rr_gyro_t {
    /**
     * Range: -32787..32787 (-2000..2000 dps)
     * Scale: 0.061
     * Offset: 0
     */
    int16_t gyro_x;

    /**
     * Range: -32787..32787 (-2000..2000 dps)
     * Scale: 0.061
     * Offset: 0
     */
    int16_t gyro_y;

    /**
     * Range: -32787..32787 (-2000..2000 dps)
     * Scale: 0.061
     * Offset: 0
     */
    int16_t gyro_z;
};

/**
 * Signals in message rr_linpot.
 *
 * All signal values are as on the CAN bus.
 */
struct mochi_rr_linpot_t {
    /**
     * Range: 0..65535 (0..655.35 cm)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t travel;
};

/**
 * Signals in message rl_accel.
 *
 * All signal values are as on the CAN bus.
 */
struct mochi_rl_accel_t {
    /**
     * Range: -32768..32768 (-8..8 g)
     * Scale: 0.000244140625
     * Offset: 0
     */
    int16_t accel_x;

    /**
     * Range: -32768..32768 (-8..8 g)
     * Scale: 0.000244140625
     * Offset: 0
     */
    int16_t accel_y;

    /**
     * Range: -32768..32768 (-8..8 g)
     * Scale: 0.000244140625
     * Offset: 0
     */
    int16_t accel_z;
};

/**
 * Signals in message rl_gyro.
 *
 * All signal values are as on the CAN bus.
 */
struct mochi_rl_gyro_t {
    /**
     * Range: -32787..32787 (-2000..2000 dps)
     * Scale: 0.061
     * Offset: 0
     */
    int16_t gyro_x;

    /**
     * Range: -32787..32787 (-2000..2000 dps)
     * Scale: 0.061
     * Offset: 0
     */
    int16_t gyro_y;

    /**
     * Range: -32787..32787 (-2000..2000 dps)
     * Scale: 0.061
     * Offset: 0
     */
    int16_t gyro_z;
};

/**
 * Signals in message rl_linpot.
 *
 * All signal values are as on the CAN bus.
 */
struct mochi_rl_linpot_t {
    /**
     * Range: 0..65535 (0..655.35 cm)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t travel;
};

/**
 * Signals in message fr_accel.
 *
 * All signal values are as on the CAN bus.
 */
struct mochi_fr_accel_t {
    /**
     * Range: -32768..32768 (-8..8 g)
     * Scale: 0.000244140625
     * Offset: 0
     */
    int16_t accel_x;

    /**
     * Range: -32768..32768 (-8..8 g)
     * Scale: 0.000244140625
     * Offset: 0
     */
    int16_t accel_y;

    /**
     * Range: -32768..32768 (-8..8 g)
     * Scale: 0.000244140625
     * Offset: 0
     */
    int16_t accel_z;
};

/**
 * Signals in message fr_gyro.
 *
 * All signal values are as on the CAN bus.
 */
struct mochi_fr_gyro_t {
    /**
     * Range: -32787..32787 (-2000..2000 dps)
     * Scale: 0.061
     * Offset: 0
     */
    int16_t gyro_x;

    /**
     * Range: -32787..32787 (-2000..2000 dps)
     * Scale: 0.061
     * Offset: 0
     */
    int16_t gyro_y;

    /**
     * Range: -32787..32787 (-2000..2000 dps)
     * Scale: 0.061
     * Offset: 0
     */
    int16_t gyro_z;
};

/**
 * Signals in message fr_linpot.
 *
 * All signal values are as on the CAN bus.
 */
struct mochi_fr_linpot_t {
    /**
     * Range: 0..65535 (0..655.35 cm)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t travel;
};

/**
 * Signals in message fl_accel.
 *
 * All signal values are as on the CAN bus.
 */
struct mochi_fl_accel_t {
    /**
     * Range: -32768..32768 (-8..8 g)
     * Scale: 0.000244140625
     * Offset: 0
     */
    int16_t accel_x;

    /**
     * Range: -32768..32768 (-8..8 g)
     * Scale: 0.000244140625
     * Offset: 0
     */
    int16_t accel_y;

    /**
     * Range: -32768..32768 (-8..8 g)
     * Scale: 0.000244140625
     * Offset: 0
     */
    int16_t accel_z;
};

/**
 * Signals in message fl_gyro.
 *
 * All signal values are as on the CAN bus.
 */
struct mochi_fl_gyro_t {
    /**
     * Range: -32787..32787 (-2000..2000 dps)
     * Scale: 0.061
     * Offset: 0
     */
    int16_t gyro_x;

    /**
     * Range: -32787..32787 (-2000..2000 dps)
     * Scale: 0.061
     * Offset: 0
     */
    int16_t gyro_y;

    /**
     * Range: -32787..32787 (-2000..2000 dps)
     * Scale: 0.061
     * Offset: 0
     */
    int16_t gyro_z;
};

/**
 * Signals in message fl_linpot.
 *
 * All signal values are as on the CAN bus.
 */
struct mochi_fl_linpot_t {
    /**
     * Range: 0..65535 (0..655.35 cm)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t travel;
};

/**
 * Signals in message speedometer.
 *
 * All signal values are as on the CAN bus.
 */
struct mochi_speedometer_t {
    /**
     * Range: 0..65535 (0..65535 km/h)
     * Scale: 1
     * Offset: 0
     */
    uint16_t speed;
};

/**
 * Signals in message tachometer.
 *
 * All signal values are as on the CAN bus.
 */
struct mochi_tachometer_t {
    /**
     * Range: 0..65535 (0..65535 rpm)
     * Scale: 1
     * Offset: 0
     */
    uint16_t rpm;
};

/**
 * Pack message rr_accel.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int mochi_rr_accel_pack(
    uint8_t *dst_p,
    const struct mochi_rr_accel_t *src_p,
    size_t size);

/**
 * Unpack message rr_accel.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int mochi_rr_accel_unpack(
    struct mochi_rr_accel_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from rr_accel.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int mochi_rr_accel_init(struct mochi_rr_accel_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t mochi_rr_accel_accel_x_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_rr_accel_accel_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_rr_accel_accel_x_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t mochi_rr_accel_accel_y_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_rr_accel_accel_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_rr_accel_accel_y_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t mochi_rr_accel_accel_z_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_rr_accel_accel_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_rr_accel_accel_z_is_in_range(int16_t value);

/**
 * Pack message rr_gyro.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int mochi_rr_gyro_pack(
    uint8_t *dst_p,
    const struct mochi_rr_gyro_t *src_p,
    size_t size);

/**
 * Unpack message rr_gyro.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int mochi_rr_gyro_unpack(
    struct mochi_rr_gyro_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from rr_gyro.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int mochi_rr_gyro_init(struct mochi_rr_gyro_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t mochi_rr_gyro_gyro_x_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_rr_gyro_gyro_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_rr_gyro_gyro_x_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t mochi_rr_gyro_gyro_y_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_rr_gyro_gyro_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_rr_gyro_gyro_y_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t mochi_rr_gyro_gyro_z_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_rr_gyro_gyro_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_rr_gyro_gyro_z_is_in_range(int16_t value);

/**
 * Pack message rr_linpot.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int mochi_rr_linpot_pack(
    uint8_t *dst_p,
    const struct mochi_rr_linpot_t *src_p,
    size_t size);

/**
 * Unpack message rr_linpot.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int mochi_rr_linpot_unpack(
    struct mochi_rr_linpot_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from rr_linpot.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int mochi_rr_linpot_init(struct mochi_rr_linpot_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t mochi_rr_linpot_travel_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_rr_linpot_travel_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_rr_linpot_travel_is_in_range(uint16_t value);

/**
 * Pack message rl_accel.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int mochi_rl_accel_pack(
    uint8_t *dst_p,
    const struct mochi_rl_accel_t *src_p,
    size_t size);

/**
 * Unpack message rl_accel.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int mochi_rl_accel_unpack(
    struct mochi_rl_accel_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from rl_accel.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int mochi_rl_accel_init(struct mochi_rl_accel_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t mochi_rl_accel_accel_x_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_rl_accel_accel_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_rl_accel_accel_x_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t mochi_rl_accel_accel_y_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_rl_accel_accel_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_rl_accel_accel_y_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t mochi_rl_accel_accel_z_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_rl_accel_accel_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_rl_accel_accel_z_is_in_range(int16_t value);

/**
 * Pack message rl_gyro.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int mochi_rl_gyro_pack(
    uint8_t *dst_p,
    const struct mochi_rl_gyro_t *src_p,
    size_t size);

/**
 * Unpack message rl_gyro.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int mochi_rl_gyro_unpack(
    struct mochi_rl_gyro_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from rl_gyro.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int mochi_rl_gyro_init(struct mochi_rl_gyro_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t mochi_rl_gyro_gyro_x_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_rl_gyro_gyro_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_rl_gyro_gyro_x_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t mochi_rl_gyro_gyro_y_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_rl_gyro_gyro_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_rl_gyro_gyro_y_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t mochi_rl_gyro_gyro_z_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_rl_gyro_gyro_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_rl_gyro_gyro_z_is_in_range(int16_t value);

/**
 * Pack message rl_linpot.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int mochi_rl_linpot_pack(
    uint8_t *dst_p,
    const struct mochi_rl_linpot_t *src_p,
    size_t size);

/**
 * Unpack message rl_linpot.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int mochi_rl_linpot_unpack(
    struct mochi_rl_linpot_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from rl_linpot.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int mochi_rl_linpot_init(struct mochi_rl_linpot_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t mochi_rl_linpot_travel_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_rl_linpot_travel_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_rl_linpot_travel_is_in_range(uint16_t value);

/**
 * Pack message fr_accel.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int mochi_fr_accel_pack(
    uint8_t *dst_p,
    const struct mochi_fr_accel_t *src_p,
    size_t size);

/**
 * Unpack message fr_accel.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int mochi_fr_accel_unpack(
    struct mochi_fr_accel_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from fr_accel.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int mochi_fr_accel_init(struct mochi_fr_accel_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t mochi_fr_accel_accel_x_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_fr_accel_accel_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_fr_accel_accel_x_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t mochi_fr_accel_accel_y_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_fr_accel_accel_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_fr_accel_accel_y_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t mochi_fr_accel_accel_z_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_fr_accel_accel_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_fr_accel_accel_z_is_in_range(int16_t value);

/**
 * Pack message fr_gyro.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int mochi_fr_gyro_pack(
    uint8_t *dst_p,
    const struct mochi_fr_gyro_t *src_p,
    size_t size);

/**
 * Unpack message fr_gyro.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int mochi_fr_gyro_unpack(
    struct mochi_fr_gyro_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from fr_gyro.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int mochi_fr_gyro_init(struct mochi_fr_gyro_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t mochi_fr_gyro_gyro_x_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_fr_gyro_gyro_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_fr_gyro_gyro_x_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t mochi_fr_gyro_gyro_y_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_fr_gyro_gyro_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_fr_gyro_gyro_y_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t mochi_fr_gyro_gyro_z_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_fr_gyro_gyro_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_fr_gyro_gyro_z_is_in_range(int16_t value);

/**
 * Pack message fr_linpot.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int mochi_fr_linpot_pack(
    uint8_t *dst_p,
    const struct mochi_fr_linpot_t *src_p,
    size_t size);

/**
 * Unpack message fr_linpot.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int mochi_fr_linpot_unpack(
    struct mochi_fr_linpot_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from fr_linpot.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int mochi_fr_linpot_init(struct mochi_fr_linpot_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t mochi_fr_linpot_travel_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_fr_linpot_travel_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_fr_linpot_travel_is_in_range(uint16_t value);

/**
 * Pack message fl_accel.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int mochi_fl_accel_pack(
    uint8_t *dst_p,
    const struct mochi_fl_accel_t *src_p,
    size_t size);

/**
 * Unpack message fl_accel.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int mochi_fl_accel_unpack(
    struct mochi_fl_accel_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from fl_accel.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int mochi_fl_accel_init(struct mochi_fl_accel_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t mochi_fl_accel_accel_x_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_fl_accel_accel_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_fl_accel_accel_x_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t mochi_fl_accel_accel_y_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_fl_accel_accel_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_fl_accel_accel_y_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t mochi_fl_accel_accel_z_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_fl_accel_accel_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_fl_accel_accel_z_is_in_range(int16_t value);

/**
 * Pack message fl_gyro.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int mochi_fl_gyro_pack(
    uint8_t *dst_p,
    const struct mochi_fl_gyro_t *src_p,
    size_t size);

/**
 * Unpack message fl_gyro.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int mochi_fl_gyro_unpack(
    struct mochi_fl_gyro_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from fl_gyro.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int mochi_fl_gyro_init(struct mochi_fl_gyro_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t mochi_fl_gyro_gyro_x_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_fl_gyro_gyro_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_fl_gyro_gyro_x_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t mochi_fl_gyro_gyro_y_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_fl_gyro_gyro_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_fl_gyro_gyro_y_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t mochi_fl_gyro_gyro_z_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_fl_gyro_gyro_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_fl_gyro_gyro_z_is_in_range(int16_t value);

/**
 * Pack message fl_linpot.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int mochi_fl_linpot_pack(
    uint8_t *dst_p,
    const struct mochi_fl_linpot_t *src_p,
    size_t size);

/**
 * Unpack message fl_linpot.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int mochi_fl_linpot_unpack(
    struct mochi_fl_linpot_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from fl_linpot.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int mochi_fl_linpot_init(struct mochi_fl_linpot_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t mochi_fl_linpot_travel_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_fl_linpot_travel_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_fl_linpot_travel_is_in_range(uint16_t value);

/**
 * Pack message speedometer.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int mochi_speedometer_pack(
    uint8_t *dst_p,
    const struct mochi_speedometer_t *src_p,
    size_t size);

/**
 * Unpack message speedometer.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int mochi_speedometer_unpack(
    struct mochi_speedometer_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from speedometer.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int mochi_speedometer_init(struct mochi_speedometer_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t mochi_speedometer_speed_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_speedometer_speed_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_speedometer_speed_is_in_range(uint16_t value);

/**
 * Pack message tachometer.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int mochi_tachometer_pack(
    uint8_t *dst_p,
    const struct mochi_tachometer_t *src_p,
    size_t size);

/**
 * Unpack message tachometer.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int mochi_tachometer_unpack(
    struct mochi_tachometer_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from tachometer.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int mochi_tachometer_init(struct mochi_tachometer_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t mochi_tachometer_rpm_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double mochi_tachometer_rpm_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool mochi_tachometer_rpm_is_in_range(uint16_t value);


#ifdef __cplusplus
}
#endif

#endif
