C:\Users\jordi\Apps\xpack-openocd-0.12.0-7-win32-x64\xpack-openocd-0.12.0-7\bin\openocd.exe ^
  -f "C:\Users\jordi\BajaFirmware\firmware\templates\rear_rtos\openocd.cfg" ^
  -c "gdb port disabled" ^
  -c "tcl port disabled" ^
  -c "telnet port disabled" ^
  -c "init" ^
  -c "reset run" ^
  -c "sleep 500" ^
  -c "rtt setup 0x20000000 0x20000" ^
  -c "rtt start" ^
  -c "rtt server start 19021 1"