/usb_cam:
  ros__parameters:
    video_device: /dev/video0
    framerate: 15.0
    image_width: 640
    image_height: 480
    pixel_format: mjpeg2rgb
    image_raw:
      disable_pub_plugins:
        - compressedDepth
        - theora