services:
  mochi_can_bridge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mochi_can
    volumes:
      - /home/ubcbaja/firmware/logs:/logs
    network_mode: "host"
    privileged: true
    environment:
      - RCUTILS_COLORIZED_OUTPUT=1
      - CAN_INTERFACE=can0
    restart: unless-stopped

  mochi_dash_gui:
    build:
      context: .
      dockerfile: Dockerfile.gui
    container_name: mochi_gui
    volumes:
      # Mount the local gui folder into the container workspace
      - ./gui:/ros2_ws/gui
    network_mode: "host"
    privileged: true
    environment:
      # Force Qt to use EGLFS for headless rendering on the Pi
      - QT_QPA_PLATFORM=eglfs
      - QT_QPA_EGLFS_ALWAYS_SET_MODE=1
    devices:
      # Give the container access to the Pi's GPU hardware
      - "/dev/dri:/dev/dri"
    restart: unless-stopped