services:
  mochi_can_bridge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros2_canopen_proxy
    network_mode: "host"
    privileged: true
    environment:
      - RCUTILS_COLORIZED_OUTPUT=1
    restart: unless-stopped