services:
  mochi_can_bridge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros2_canopen_proxy
    volumes:
      - /home/ubcbaja/firmware/logs:/logs
    network_mode: "host"
    privileged: true
    environment:
      - RCUTILS_COLORIZED_OUTPUT=1
      - CAN_INTERFACE=can0
    restart: unless-stopped