/**
 * @file mochi.c
 *
 * @brief This source file was generated by cantools version 40.7.1 Fri Jul 17 12:19:15 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "mochi.h"

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int mochi_rr_accel_pack(
    uint8_t *dst_p,
    const struct mochi_rr_accel_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    accel_x = (uint16_t)src_p->accel_x;
    dst_p[0] |= pack_left_shift_u16(accel_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(accel_x, 8u, 0xffu);
    accel_y = (uint16_t)src_p->accel_y;
    dst_p[2] |= pack_left_shift_u16(accel_y, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(accel_y, 8u, 0xffu);
    accel_z = (uint16_t)src_p->accel_z;
    dst_p[4] |= pack_left_shift_u16(accel_z, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(accel_z, 8u, 0xffu);

    return (6);
}

int mochi_rr_accel_unpack(
    struct mochi_rr_accel_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;

    if (size < 6u) {
        return (-EINVAL);
    }

    accel_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    accel_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->accel_x = (int16_t)accel_x;
    accel_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    accel_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->accel_y = (int16_t)accel_y;
    accel_z = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    accel_z |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->accel_z = (int16_t)accel_z;

    return (0);
}

int mochi_rr_accel_init(struct mochi_rr_accel_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mochi_rr_accel_t));

    return 0;
}

int16_t mochi_rr_accel_accel_x_encode(double value)
{
    return (int16_t)(value / 0.000244140625);
}

double mochi_rr_accel_accel_x_decode(int16_t value)
{
    return ((double)value * 0.000244140625);
}

bool mochi_rr_accel_accel_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t mochi_rr_accel_accel_y_encode(double value)
{
    return (int16_t)(value / 0.000244140625);
}

double mochi_rr_accel_accel_y_decode(int16_t value)
{
    return ((double)value * 0.000244140625);
}

bool mochi_rr_accel_accel_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t mochi_rr_accel_accel_z_encode(double value)
{
    return (int16_t)(value / 0.000244140625);
}

double mochi_rr_accel_accel_z_decode(int16_t value)
{
    return ((double)value * 0.000244140625);
}

bool mochi_rr_accel_accel_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int mochi_rr_gyro_pack(
    uint8_t *dst_p,
    const struct mochi_rr_gyro_t *src_p,
    size_t size)
{
    uint16_t gyro_x;
    uint16_t gyro_y;
    uint16_t gyro_z;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    gyro_x = (uint16_t)src_p->gyro_x;
    dst_p[0] |= pack_left_shift_u16(gyro_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(gyro_x, 8u, 0xffu);
    gyro_y = (uint16_t)src_p->gyro_y;
    dst_p[2] |= pack_left_shift_u16(gyro_y, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(gyro_y, 8u, 0xffu);
    gyro_z = (uint16_t)src_p->gyro_z;
    dst_p[4] |= pack_left_shift_u16(gyro_z, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(gyro_z, 8u, 0xffu);

    return (6);
}

int mochi_rr_gyro_unpack(
    struct mochi_rr_gyro_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t gyro_x;
    uint16_t gyro_y;
    uint16_t gyro_z;

    if (size < 6u) {
        return (-EINVAL);
    }

    gyro_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    gyro_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->gyro_x = (int16_t)gyro_x;
    gyro_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    gyro_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->gyro_y = (int16_t)gyro_y;
    gyro_z = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    gyro_z |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->gyro_z = (int16_t)gyro_z;

    return (0);
}

int mochi_rr_gyro_init(struct mochi_rr_gyro_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mochi_rr_gyro_t));

    return 0;
}

int16_t mochi_rr_gyro_gyro_x_encode(double value)
{
    return (int16_t)(value / 0.061);
}

double mochi_rr_gyro_gyro_x_decode(int16_t value)
{
    return ((double)value * 0.061);
}

bool mochi_rr_gyro_gyro_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t mochi_rr_gyro_gyro_y_encode(double value)
{
    return (int16_t)(value / 0.061);
}

double mochi_rr_gyro_gyro_y_decode(int16_t value)
{
    return ((double)value * 0.061);
}

bool mochi_rr_gyro_gyro_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t mochi_rr_gyro_gyro_z_encode(double value)
{
    return (int16_t)(value / 0.061);
}

double mochi_rr_gyro_gyro_z_decode(int16_t value)
{
    return ((double)value * 0.061);
}

bool mochi_rr_gyro_gyro_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int mochi_rr_linpot_pack(
    uint8_t *dst_p,
    const struct mochi_rr_linpot_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u16(src_p->travel, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->travel, 8u, 0xffu);

    return (2);
}

int mochi_rr_linpot_unpack(
    struct mochi_rr_linpot_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->travel = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->travel |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int mochi_rr_linpot_init(struct mochi_rr_linpot_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mochi_rr_linpot_t));

    return 0;
}

uint16_t mochi_rr_linpot_travel_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double mochi_rr_linpot_travel_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool mochi_rr_linpot_travel_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int mochi_rl_accel_pack(
    uint8_t *dst_p,
    const struct mochi_rl_accel_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    accel_x = (uint16_t)src_p->accel_x;
    dst_p[0] |= pack_left_shift_u16(accel_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(accel_x, 8u, 0xffu);
    accel_y = (uint16_t)src_p->accel_y;
    dst_p[2] |= pack_left_shift_u16(accel_y, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(accel_y, 8u, 0xffu);
    accel_z = (uint16_t)src_p->accel_z;
    dst_p[4] |= pack_left_shift_u16(accel_z, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(accel_z, 8u, 0xffu);

    return (6);
}

int mochi_rl_accel_unpack(
    struct mochi_rl_accel_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;

    if (size < 6u) {
        return (-EINVAL);
    }

    accel_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    accel_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->accel_x = (int16_t)accel_x;
    accel_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    accel_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->accel_y = (int16_t)accel_y;
    accel_z = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    accel_z |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->accel_z = (int16_t)accel_z;

    return (0);
}

int mochi_rl_accel_init(struct mochi_rl_accel_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mochi_rl_accel_t));

    return 0;
}

int16_t mochi_rl_accel_accel_x_encode(double value)
{
    return (int16_t)(value / 0.000244140625);
}

double mochi_rl_accel_accel_x_decode(int16_t value)
{
    return ((double)value * 0.000244140625);
}

bool mochi_rl_accel_accel_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t mochi_rl_accel_accel_y_encode(double value)
{
    return (int16_t)(value / 0.000244140625);
}

double mochi_rl_accel_accel_y_decode(int16_t value)
{
    return ((double)value * 0.000244140625);
}

bool mochi_rl_accel_accel_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t mochi_rl_accel_accel_z_encode(double value)
{
    return (int16_t)(value / 0.000244140625);
}

double mochi_rl_accel_accel_z_decode(int16_t value)
{
    return ((double)value * 0.000244140625);
}

bool mochi_rl_accel_accel_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int mochi_rl_gyro_pack(
    uint8_t *dst_p,
    const struct mochi_rl_gyro_t *src_p,
    size_t size)
{
    uint16_t gyro_x;
    uint16_t gyro_y;
    uint16_t gyro_z;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    gyro_x = (uint16_t)src_p->gyro_x;
    dst_p[0] |= pack_left_shift_u16(gyro_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(gyro_x, 8u, 0xffu);
    gyro_y = (uint16_t)src_p->gyro_y;
    dst_p[2] |= pack_left_shift_u16(gyro_y, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(gyro_y, 8u, 0xffu);
    gyro_z = (uint16_t)src_p->gyro_z;
    dst_p[4] |= pack_left_shift_u16(gyro_z, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(gyro_z, 8u, 0xffu);

    return (6);
}

int mochi_rl_gyro_unpack(
    struct mochi_rl_gyro_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t gyro_x;
    uint16_t gyro_y;
    uint16_t gyro_z;

    if (size < 6u) {
        return (-EINVAL);
    }

    gyro_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    gyro_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->gyro_x = (int16_t)gyro_x;
    gyro_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    gyro_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->gyro_y = (int16_t)gyro_y;
    gyro_z = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    gyro_z |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->gyro_z = (int16_t)gyro_z;

    return (0);
}

int mochi_rl_gyro_init(struct mochi_rl_gyro_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mochi_rl_gyro_t));

    return 0;
}

int16_t mochi_rl_gyro_gyro_x_encode(double value)
{
    return (int16_t)(value / 0.061);
}

double mochi_rl_gyro_gyro_x_decode(int16_t value)
{
    return ((double)value * 0.061);
}

bool mochi_rl_gyro_gyro_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t mochi_rl_gyro_gyro_y_encode(double value)
{
    return (int16_t)(value / 0.061);
}

double mochi_rl_gyro_gyro_y_decode(int16_t value)
{
    return ((double)value * 0.061);
}

bool mochi_rl_gyro_gyro_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t mochi_rl_gyro_gyro_z_encode(double value)
{
    return (int16_t)(value / 0.061);
}

double mochi_rl_gyro_gyro_z_decode(int16_t value)
{
    return ((double)value * 0.061);
}

bool mochi_rl_gyro_gyro_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int mochi_rl_linpot_pack(
    uint8_t *dst_p,
    const struct mochi_rl_linpot_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u16(src_p->travel, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->travel, 8u, 0xffu);

    return (2);
}

int mochi_rl_linpot_unpack(
    struct mochi_rl_linpot_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->travel = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->travel |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int mochi_rl_linpot_init(struct mochi_rl_linpot_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mochi_rl_linpot_t));

    return 0;
}

uint16_t mochi_rl_linpot_travel_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double mochi_rl_linpot_travel_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool mochi_rl_linpot_travel_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int mochi_fr_accel_pack(
    uint8_t *dst_p,
    const struct mochi_fr_accel_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    accel_x = (uint16_t)src_p->accel_x;
    dst_p[0] |= pack_left_shift_u16(accel_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(accel_x, 8u, 0xffu);
    accel_y = (uint16_t)src_p->accel_y;
    dst_p[2] |= pack_left_shift_u16(accel_y, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(accel_y, 8u, 0xffu);
    accel_z = (uint16_t)src_p->accel_z;
    dst_p[4] |= pack_left_shift_u16(accel_z, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(accel_z, 8u, 0xffu);

    return (6);
}

int mochi_fr_accel_unpack(
    struct mochi_fr_accel_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;

    if (size < 6u) {
        return (-EINVAL);
    }

    accel_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    accel_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->accel_x = (int16_t)accel_x;
    accel_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    accel_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->accel_y = (int16_t)accel_y;
    accel_z = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    accel_z |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->accel_z = (int16_t)accel_z;

    return (0);
}

int mochi_fr_accel_init(struct mochi_fr_accel_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mochi_fr_accel_t));

    return 0;
}

int16_t mochi_fr_accel_accel_x_encode(double value)
{
    return (int16_t)(value / 0.000244140625);
}

double mochi_fr_accel_accel_x_decode(int16_t value)
{
    return ((double)value * 0.000244140625);
}

bool mochi_fr_accel_accel_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t mochi_fr_accel_accel_y_encode(double value)
{
    return (int16_t)(value / 0.000244140625);
}

double mochi_fr_accel_accel_y_decode(int16_t value)
{
    return ((double)value * 0.000244140625);
}

bool mochi_fr_accel_accel_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t mochi_fr_accel_accel_z_encode(double value)
{
    return (int16_t)(value / 0.000244140625);
}

double mochi_fr_accel_accel_z_decode(int16_t value)
{
    return ((double)value * 0.000244140625);
}

bool mochi_fr_accel_accel_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int mochi_fr_gyro_pack(
    uint8_t *dst_p,
    const struct mochi_fr_gyro_t *src_p,
    size_t size)
{
    uint16_t gyro_x;
    uint16_t gyro_y;
    uint16_t gyro_z;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    gyro_x = (uint16_t)src_p->gyro_x;
    dst_p[0] |= pack_left_shift_u16(gyro_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(gyro_x, 8u, 0xffu);
    gyro_y = (uint16_t)src_p->gyro_y;
    dst_p[2] |= pack_left_shift_u16(gyro_y, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(gyro_y, 8u, 0xffu);
    gyro_z = (uint16_t)src_p->gyro_z;
    dst_p[4] |= pack_left_shift_u16(gyro_z, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(gyro_z, 8u, 0xffu);

    return (6);
}

int mochi_fr_gyro_unpack(
    struct mochi_fr_gyro_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t gyro_x;
    uint16_t gyro_y;
    uint16_t gyro_z;

    if (size < 6u) {
        return (-EINVAL);
    }

    gyro_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    gyro_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->gyro_x = (int16_t)gyro_x;
    gyro_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    gyro_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->gyro_y = (int16_t)gyro_y;
    gyro_z = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    gyro_z |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->gyro_z = (int16_t)gyro_z;

    return (0);
}

int mochi_fr_gyro_init(struct mochi_fr_gyro_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mochi_fr_gyro_t));

    return 0;
}

int16_t mochi_fr_gyro_gyro_x_encode(double value)
{
    return (int16_t)(value / 0.061);
}

double mochi_fr_gyro_gyro_x_decode(int16_t value)
{
    return ((double)value * 0.061);
}

bool mochi_fr_gyro_gyro_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t mochi_fr_gyro_gyro_y_encode(double value)
{
    return (int16_t)(value / 0.061);
}

double mochi_fr_gyro_gyro_y_decode(int16_t value)
{
    return ((double)value * 0.061);
}

bool mochi_fr_gyro_gyro_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t mochi_fr_gyro_gyro_z_encode(double value)
{
    return (int16_t)(value / 0.061);
}

double mochi_fr_gyro_gyro_z_decode(int16_t value)
{
    return ((double)value * 0.061);
}

bool mochi_fr_gyro_gyro_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int mochi_fr_linpot_pack(
    uint8_t *dst_p,
    const struct mochi_fr_linpot_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u16(src_p->travel, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->travel, 8u, 0xffu);

    return (2);
}

int mochi_fr_linpot_unpack(
    struct mochi_fr_linpot_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->travel = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->travel |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int mochi_fr_linpot_init(struct mochi_fr_linpot_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mochi_fr_linpot_t));

    return 0;
}

uint16_t mochi_fr_linpot_travel_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double mochi_fr_linpot_travel_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool mochi_fr_linpot_travel_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int mochi_fl_accel_pack(
    uint8_t *dst_p,
    const struct mochi_fl_accel_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    accel_x = (uint16_t)src_p->accel_x;
    dst_p[0] |= pack_left_shift_u16(accel_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(accel_x, 8u, 0xffu);
    accel_y = (uint16_t)src_p->accel_y;
    dst_p[2] |= pack_left_shift_u16(accel_y, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(accel_y, 8u, 0xffu);
    accel_z = (uint16_t)src_p->accel_z;
    dst_p[4] |= pack_left_shift_u16(accel_z, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(accel_z, 8u, 0xffu);

    return (6);
}

int mochi_fl_accel_unpack(
    struct mochi_fl_accel_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;

    if (size < 6u) {
        return (-EINVAL);
    }

    accel_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    accel_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->accel_x = (int16_t)accel_x;
    accel_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    accel_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->accel_y = (int16_t)accel_y;
    accel_z = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    accel_z |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->accel_z = (int16_t)accel_z;

    return (0);
}

int mochi_fl_accel_init(struct mochi_fl_accel_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mochi_fl_accel_t));

    return 0;
}

int16_t mochi_fl_accel_accel_x_encode(double value)
{
    return (int16_t)(value / 0.000244140625);
}

double mochi_fl_accel_accel_x_decode(int16_t value)
{
    return ((double)value * 0.000244140625);
}

bool mochi_fl_accel_accel_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t mochi_fl_accel_accel_y_encode(double value)
{
    return (int16_t)(value / 0.000244140625);
}

double mochi_fl_accel_accel_y_decode(int16_t value)
{
    return ((double)value * 0.000244140625);
}

bool mochi_fl_accel_accel_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t mochi_fl_accel_accel_z_encode(double value)
{
    return (int16_t)(value / 0.000244140625);
}

double mochi_fl_accel_accel_z_decode(int16_t value)
{
    return ((double)value * 0.000244140625);
}

bool mochi_fl_accel_accel_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int mochi_fl_gyro_pack(
    uint8_t *dst_p,
    const struct mochi_fl_gyro_t *src_p,
    size_t size)
{
    uint16_t gyro_x;
    uint16_t gyro_y;
    uint16_t gyro_z;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    gyro_x = (uint16_t)src_p->gyro_x;
    dst_p[0] |= pack_left_shift_u16(gyro_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(gyro_x, 8u, 0xffu);
    gyro_y = (uint16_t)src_p->gyro_y;
    dst_p[2] |= pack_left_shift_u16(gyro_y, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(gyro_y, 8u, 0xffu);
    gyro_z = (uint16_t)src_p->gyro_z;
    dst_p[4] |= pack_left_shift_u16(gyro_z, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(gyro_z, 8u, 0xffu);

    return (6);
}

int mochi_fl_gyro_unpack(
    struct mochi_fl_gyro_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t gyro_x;
    uint16_t gyro_y;
    uint16_t gyro_z;

    if (size < 6u) {
        return (-EINVAL);
    }

    gyro_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    gyro_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->gyro_x = (int16_t)gyro_x;
    gyro_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    gyro_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->gyro_y = (int16_t)gyro_y;
    gyro_z = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    gyro_z |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->gyro_z = (int16_t)gyro_z;

    return (0);
}

int mochi_fl_gyro_init(struct mochi_fl_gyro_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mochi_fl_gyro_t));

    return 0;
}

int16_t mochi_fl_gyro_gyro_x_encode(double value)
{
    return (int16_t)(value / 0.061);
}

double mochi_fl_gyro_gyro_x_decode(int16_t value)
{
    return ((double)value * 0.061);
}

bool mochi_fl_gyro_gyro_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t mochi_fl_gyro_gyro_y_encode(double value)
{
    return (int16_t)(value / 0.061);
}

double mochi_fl_gyro_gyro_y_decode(int16_t value)
{
    return ((double)value * 0.061);
}

bool mochi_fl_gyro_gyro_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t mochi_fl_gyro_gyro_z_encode(double value)
{
    return (int16_t)(value / 0.061);
}

double mochi_fl_gyro_gyro_z_decode(int16_t value)
{
    return ((double)value * 0.061);
}

bool mochi_fl_gyro_gyro_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int mochi_fl_linpot_pack(
    uint8_t *dst_p,
    const struct mochi_fl_linpot_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u16(src_p->travel, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->travel, 8u, 0xffu);

    return (2);
}

int mochi_fl_linpot_unpack(
    struct mochi_fl_linpot_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->travel = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->travel |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int mochi_fl_linpot_init(struct mochi_fl_linpot_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mochi_fl_linpot_t));

    return 0;
}

uint16_t mochi_fl_linpot_travel_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double mochi_fl_linpot_travel_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool mochi_fl_linpot_travel_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int mochi_speedometer_pack(
    uint8_t *dst_p,
    const struct mochi_speedometer_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u16(src_p->speed, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->speed, 8u, 0xffu);

    return (2);
}

int mochi_speedometer_unpack(
    struct mochi_speedometer_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->speed = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->speed |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int mochi_speedometer_init(struct mochi_speedometer_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mochi_speedometer_t));

    return 0;
}

uint16_t mochi_speedometer_speed_encode(double value)
{
    return (uint16_t)(value);
}

double mochi_speedometer_speed_decode(uint16_t value)
{
    return ((double)value);
}

bool mochi_speedometer_speed_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int mochi_tachometer_pack(
    uint8_t *dst_p,
    const struct mochi_tachometer_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u16(src_p->rpm, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->rpm, 8u, 0xffu);

    return (2);
}

int mochi_tachometer_unpack(
    struct mochi_tachometer_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->rpm = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->rpm |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int mochi_tachometer_init(struct mochi_tachometer_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mochi_tachometer_t));

    return 0;
}

uint16_t mochi_tachometer_rpm_encode(double value)
{
    return (uint16_t)(value);
}

double mochi_tachometer_rpm_decode(uint16_t value)
{
    return ((double)value);
}

bool mochi_tachometer_rpm_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int mochi_fl_accel_pack(
    uint8_t *dst_p,
    const struct mochi_fl_accel_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    accel_x = (uint16_t)src_p->accel_x;
    dst_p[0] |= pack_left_shift_u16(accel_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(accel_x, 8u, 0xffu);
    accel_y = (uint16_t)src_p->accel_y;
    dst_p[2] |= pack_left_shift_u16(accel_y, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(accel_y, 8u, 0xffu);
    accel_z = (uint16_t)src_p->accel_z;
    dst_p[4] |= pack_left_shift_u16(accel_z, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(accel_z, 8u, 0xffu);

    return (6);
}

int mochi_fl_accel_unpack(
    struct mochi_fl_accel_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;

    if (size < 6u) {
        return (-EINVAL);
    }

    accel_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    accel_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->accel_x = (int16_t)accel_x;
    accel_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    accel_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->accel_y = (int16_t)accel_y;
    accel_z = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    accel_z |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->accel_z = (int16_t)accel_z;

    return (0);
}

int mochi_fl_accel_init(struct mochi_fl_accel_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mochi_fl_accel_t));

    return 0;
}

int16_t mochi_fl_accel_accel_x_encode(double value)
{
    return (int16_t)(value / 0.000244140625);
}

double mochi_fl_accel_accel_x_decode(int16_t value)
{
    return ((double)value * 0.000244140625);
}

bool mochi_fl_accel_accel_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t mochi_fl_accel_accel_y_encode(double value)
{
    return (int16_t)(value / 0.000244140625);
}

double mochi_fl_accel_accel_y_decode(int16_t value)
{
    return ((double)value * 0.000244140625);
}

bool mochi_fl_accel_accel_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t mochi_fl_accel_accel_z_encode(double value)
{
    return (int16_t)(value / 0.000244140625);
}

double mochi_fl_accel_accel_z_decode(int16_t value)
{
    return ((double)value * 0.000244140625);
}

bool mochi_fl_accel_accel_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int mochi_fl_gyro_pack(
    uint8_t *dst_p,
    const struct mochi_fl_gyro_t *src_p,
    size_t size)
{
    uint16_t gyro_x;
    uint16_t gyro_y;
    uint16_t gyro_z;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    gyro_x = (uint16_t)src_p->gyro_x;
    dst_p[0] |= pack_left_shift_u16(gyro_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(gyro_x, 8u, 0xffu);
    gyro_y = (uint16_t)src_p->gyro_y;
    dst_p[2] |= pack_left_shift_u16(gyro_y, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(gyro_y, 8u, 0xffu);
    gyro_z = (uint16_t)src_p->gyro_z;
    dst_p[4] |= pack_left_shift_u16(gyro_z, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(gyro_z, 8u, 0xffu);

    return (6);
}

int mochi_fl_gyro_unpack(
    struct mochi_fl_gyro_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t gyro_x;
    uint16_t gyro_y;
    uint16_t gyro_z;

    if (size < 6u) {
        return (-EINVAL);
    }

    gyro_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    gyro_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->gyro_x = (int16_t)gyro_x;
    gyro_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    gyro_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->gyro_y = (int16_t)gyro_y;
    gyro_z = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    gyro_z |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->gyro_z = (int16_t)gyro_z;

    return (0);
}

int mochi_fl_gyro_init(struct mochi_fl_gyro_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mochi_fl_gyro_t));

    return 0;
}

int16_t mochi_fl_gyro_gyro_x_encode(double value)
{
    return (int16_t)(value / 0.061);
}

double mochi_fl_gyro_gyro_x_decode(int16_t value)
{
    return ((double)value * 0.061);
}

bool mochi_fl_gyro_gyro_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t mochi_fl_gyro_gyro_y_encode(double value)
{
    return (int16_t)(value / 0.061);
}

double mochi_fl_gyro_gyro_y_decode(int16_t value)
{
    return ((double)value * 0.061);
}

bool mochi_fl_gyro_gyro_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t mochi_fl_gyro_gyro_z_encode(double value)
{
    return (int16_t)(value / 0.061);
}

double mochi_fl_gyro_gyro_z_decode(int16_t value)
{
    return ((double)value * 0.061);
}

bool mochi_fl_gyro_gyro_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}
