# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\x07vehicle\"x\n\x03\x45\x43U\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\t\n\x01w\x18\x04 \x01(\x02\x12\x15\n\rscaled_linpot\x18\x05 \x01(\r\x12\x16\n\x0escaled_strain1\x18\x06 \x01(\x11\x12\x16\n\x0escaled_strain2\x18\x07 \x01(\x11\"\xe6\x01\n\rBajaTelemetry\x12\x18\n\x02\x66r\x18\x01 \x01(\x0b\x32\x0c.vehicle.ECU\x12\x18\n\x02\x66l\x18\x02 \x01(\x0b\x32\x0c.vehicle.ECU\x12\x18\n\x02rr\x18\x03 \x01(\x0b\x32\x0c.vehicle.ECU\x12\x18\n\x02rl\x18\x04 \x01(\x0b\x32\x0c.vehicle.ECU\x12\x17\n\x0fscaled_latitude\x18\x05 \x01(\x11\x12\x18\n\x10scaled_longitude\x18\x06 \x01(\x11\x12\x17\n\x0fscaled_altitude\x18\x07 \x01(\x11\x12\x14\n\x0cscaled_speed\x18\x08 \x01(\r\x12\x0b\n\x03rpm\x18\t \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ECU']._serialized_start=28
  _globals['_ECU']._serialized_end=148
  _globals['_BAJATELEMETRY']._serialized_start=151
  _globals['_BAJATELEMETRY']._serialized_end=381
# @@protoc_insertion_point(module_scope)
