/**
 * @file roxy.c
 *
 * @brief This source file was generated by cantools version 40.7.1 Wed Sep 30 13:45:09 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "roxy.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t unpack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) << shift);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int roxy_rear_daq_pack(
    uint8_t *dst_p,
    const struct roxy_rear_daq_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;
    uint16_t gyro_x;
    uint16_t gyro_y;
    uint16_t gyro_z;
    uint16_t mag_x;
    uint16_t mag_y;
    uint16_t mag_z;

    if (size < 26u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 26);

    dst_p[0] |= pack_left_shift_u8(src_p->speedometer, 0u, 0x3fu);
    dst_p[0] |= pack_left_shift_u16(src_p->tachometer, 6u, 0xc0u);
    dst_p[1] |= pack_right_shift_u16(src_p->tachometer, 2u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->tachometer, 10u, 0x03u);
    dst_p[2] |= pack_left_shift_u8(src_p->cvt_temp, 2u, 0xfcu);
    dst_p[3] |= pack_right_shift_u8(src_p->cvt_temp, 6u, 0x01u);
    dst_p[3] |= pack_left_shift_u8(src_p->ambient_temp, 1u, 0xfeu);
    dst_p[4] |= pack_left_shift_u16(src_p->linpot_r, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->linpot_r, 8u, 0x0fu);
    dst_p[5] |= pack_left_shift_u16(src_p->linpot_l, 4u, 0xf0u);
    dst_p[6] |= pack_right_shift_u16(src_p->linpot_l, 4u, 0xffu);
    accel_x = (uint16_t)src_p->accel_x;
    dst_p[7] |= pack_left_shift_u16(accel_x, 0u, 0xffu);
    dst_p[8] |= pack_right_shift_u16(accel_x, 8u, 0xffu);
    accel_y = (uint16_t)src_p->accel_y;
    dst_p[9] |= pack_left_shift_u16(accel_y, 0u, 0xffu);
    dst_p[10] |= pack_right_shift_u16(accel_y, 8u, 0xffu);
    accel_z = (uint16_t)src_p->accel_z;
    dst_p[11] |= pack_left_shift_u16(accel_z, 0u, 0xffu);
    dst_p[12] |= pack_right_shift_u16(accel_z, 8u, 0xffu);
    gyro_x = (uint16_t)src_p->gyro_x;
    dst_p[13] |= pack_left_shift_u16(gyro_x, 0u, 0xffu);
    dst_p[14] |= pack_right_shift_u16(gyro_x, 8u, 0xffu);
    gyro_y = (uint16_t)src_p->gyro_y;
    dst_p[15] |= pack_left_shift_u16(gyro_y, 0u, 0xffu);
    dst_p[16] |= pack_right_shift_u16(gyro_y, 8u, 0xffu);
    gyro_z = (uint16_t)src_p->gyro_z;
    dst_p[17] |= pack_left_shift_u16(gyro_z, 0u, 0xffu);
    dst_p[18] |= pack_right_shift_u16(gyro_z, 8u, 0xffu);
    mag_x = (uint16_t)src_p->mag_x;
    dst_p[19] |= pack_left_shift_u16(mag_x, 0u, 0xffu);
    dst_p[20] |= pack_right_shift_u16(mag_x, 8u, 0xffu);
    mag_y = (uint16_t)src_p->mag_y;
    dst_p[21] |= pack_left_shift_u16(mag_y, 0u, 0xffu);
    dst_p[22] |= pack_right_shift_u16(mag_y, 8u, 0xffu);
    mag_z = (uint16_t)src_p->mag_z;
    dst_p[23] |= pack_left_shift_u16(mag_z, 0u, 0xffu);
    dst_p[24] |= pack_right_shift_u16(mag_z, 8u, 0xffu);

    return (26);
}

int roxy_rear_daq_unpack(
    struct roxy_rear_daq_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;
    uint16_t gyro_x;
    uint16_t gyro_y;
    uint16_t gyro_z;
    uint16_t mag_x;
    uint16_t mag_y;
    uint16_t mag_z;

    if (size < 26u) {
        return (-EINVAL);
    }

    dst_p->speedometer = unpack_right_shift_u8(src_p[0], 0u, 0x3fu);
    dst_p->tachometer = unpack_right_shift_u16(src_p[0], 6u, 0xc0u);
    dst_p->tachometer |= unpack_left_shift_u16(src_p[1], 2u, 0xffu);
    dst_p->tachometer |= unpack_left_shift_u16(src_p[2], 10u, 0x03u);
    dst_p->cvt_temp = unpack_right_shift_u8(src_p[2], 2u, 0xfcu);
    dst_p->cvt_temp |= unpack_left_shift_u8(src_p[3], 6u, 0x01u);
    dst_p->ambient_temp = unpack_right_shift_u8(src_p[3], 1u, 0xfeu);
    dst_p->linpot_r = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->linpot_r |= unpack_left_shift_u16(src_p[5], 8u, 0x0fu);
    dst_p->linpot_l = unpack_right_shift_u16(src_p[5], 4u, 0xf0u);
    dst_p->linpot_l |= unpack_left_shift_u16(src_p[6], 4u, 0xffu);
    accel_x = unpack_right_shift_u16(src_p[7], 0u, 0xffu);
    accel_x |= unpack_left_shift_u16(src_p[8], 8u, 0xffu);
    dst_p->accel_x = (int16_t)accel_x;
    accel_y = unpack_right_shift_u16(src_p[9], 0u, 0xffu);
    accel_y |= unpack_left_shift_u16(src_p[10], 8u, 0xffu);
    dst_p->accel_y = (int16_t)accel_y;
    accel_z = unpack_right_shift_u16(src_p[11], 0u, 0xffu);
    accel_z |= unpack_left_shift_u16(src_p[12], 8u, 0xffu);
    dst_p->accel_z = (int16_t)accel_z;
    gyro_x = unpack_right_shift_u16(src_p[13], 0u, 0xffu);
    gyro_x |= unpack_left_shift_u16(src_p[14], 8u, 0xffu);
    dst_p->gyro_x = (int16_t)gyro_x;
    gyro_y = unpack_right_shift_u16(src_p[15], 0u, 0xffu);
    gyro_y |= unpack_left_shift_u16(src_p[16], 8u, 0xffu);
    dst_p->gyro_y = (int16_t)gyro_y;
    gyro_z = unpack_right_shift_u16(src_p[17], 0u, 0xffu);
    gyro_z |= unpack_left_shift_u16(src_p[18], 8u, 0xffu);
    dst_p->gyro_z = (int16_t)gyro_z;
    mag_x = unpack_right_shift_u16(src_p[19], 0u, 0xffu);
    mag_x |= unpack_left_shift_u16(src_p[20], 8u, 0xffu);
    dst_p->mag_x = (int16_t)mag_x;
    mag_y = unpack_right_shift_u16(src_p[21], 0u, 0xffu);
    mag_y |= unpack_left_shift_u16(src_p[22], 8u, 0xffu);
    dst_p->mag_y = (int16_t)mag_y;
    mag_z = unpack_right_shift_u16(src_p[23], 0u, 0xffu);
    mag_z |= unpack_left_shift_u16(src_p[24], 8u, 0xffu);
    dst_p->mag_z = (int16_t)mag_z;

    return (0);
}

int roxy_rear_daq_init(struct roxy_rear_daq_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct roxy_rear_daq_t));

    return 0;
}

uint8_t roxy_rear_daq_speedometer_encode(double value)
{
    return (uint8_t)(value);
}

double roxy_rear_daq_speedometer_decode(uint8_t value)
{
    return ((double)value);
}

bool roxy_rear_daq_speedometer_is_in_range(uint8_t value)
{
    return (value <= 63u);
}

uint16_t roxy_rear_daq_tachometer_encode(double value)
{
    return (uint16_t)(value);
}

double roxy_rear_daq_tachometer_decode(uint16_t value)
{
    return ((double)value);
}

bool roxy_rear_daq_tachometer_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint8_t roxy_rear_daq_cvt_temp_encode(double value)
{
    return (uint8_t)(value);
}

double roxy_rear_daq_cvt_temp_decode(uint8_t value)
{
    return ((double)value);
}

bool roxy_rear_daq_cvt_temp_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

uint8_t roxy_rear_daq_ambient_temp_encode(double value)
{
    return (uint8_t)(value);
}

double roxy_rear_daq_ambient_temp_decode(uint8_t value)
{
    return ((double)value);
}

bool roxy_rear_daq_ambient_temp_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

uint16_t roxy_rear_daq_linpot_r_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double roxy_rear_daq_linpot_r_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool roxy_rear_daq_linpot_r_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t roxy_rear_daq_linpot_l_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double roxy_rear_daq_linpot_l_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool roxy_rear_daq_linpot_l_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

int16_t roxy_rear_daq_accel_x_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double roxy_rear_daq_accel_x_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool roxy_rear_daq_accel_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t roxy_rear_daq_accel_y_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double roxy_rear_daq_accel_y_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool roxy_rear_daq_accel_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t roxy_rear_daq_accel_z_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double roxy_rear_daq_accel_z_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool roxy_rear_daq_accel_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t roxy_rear_daq_gyro_x_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double roxy_rear_daq_gyro_x_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool roxy_rear_daq_gyro_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t roxy_rear_daq_gyro_y_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double roxy_rear_daq_gyro_y_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool roxy_rear_daq_gyro_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t roxy_rear_daq_gyro_z_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double roxy_rear_daq_gyro_z_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool roxy_rear_daq_gyro_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t roxy_rear_daq_mag_x_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double roxy_rear_daq_mag_x_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool roxy_rear_daq_mag_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t roxy_rear_daq_mag_y_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double roxy_rear_daq_mag_y_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool roxy_rear_daq_mag_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t roxy_rear_daq_mag_z_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double roxy_rear_daq_mag_z_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool roxy_rear_daq_mag_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int roxy_front_daq_pack(
    uint8_t *dst_p,
    const struct roxy_front_daq_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;
    uint16_t gyro_x;
    uint16_t gyro_y;
    uint16_t gyro_z;
    uint16_t mag_x;
    uint16_t mag_y;
    uint16_t mag_z;

    if (size < 26u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 26);

    dst_p[0] |= pack_left_shift_u16(src_p->steering_angle, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->steering_angle, 8u, 0x0fu);
    dst_p[1] |= pack_left_shift_u8(src_p->brake_f, 4u, 0xf0u);
    dst_p[2] |= pack_right_shift_u8(src_p->brake_f, 4u, 0x0fu);
    dst_p[2] |= pack_left_shift_u8(src_p->brake_r, 4u, 0xf0u);
    dst_p[3] |= pack_right_shift_u8(src_p->brake_r, 4u, 0x0fu);
    dst_p[4] |= pack_left_shift_u16(src_p->linpot_r, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->linpot_r, 8u, 0x0fu);
    dst_p[5] |= pack_left_shift_u16(src_p->linpot_l, 4u, 0xf0u);
    dst_p[6] |= pack_right_shift_u16(src_p->linpot_l, 4u, 0xffu);
    accel_x = (uint16_t)src_p->accel_x;
    dst_p[7] |= pack_left_shift_u16(accel_x, 0u, 0xffu);
    dst_p[8] |= pack_right_shift_u16(accel_x, 8u, 0xffu);
    accel_y = (uint16_t)src_p->accel_y;
    dst_p[9] |= pack_left_shift_u16(accel_y, 0u, 0xffu);
    dst_p[10] |= pack_right_shift_u16(accel_y, 8u, 0xffu);
    accel_z = (uint16_t)src_p->accel_z;
    dst_p[11] |= pack_left_shift_u16(accel_z, 0u, 0xffu);
    dst_p[12] |= pack_right_shift_u16(accel_z, 8u, 0xffu);
    gyro_x = (uint16_t)src_p->gyro_x;
    dst_p[13] |= pack_left_shift_u16(gyro_x, 0u, 0xffu);
    dst_p[14] |= pack_right_shift_u16(gyro_x, 8u, 0xffu);
    gyro_y = (uint16_t)src_p->gyro_y;
    dst_p[15] |= pack_left_shift_u16(gyro_y, 0u, 0xffu);
    dst_p[16] |= pack_right_shift_u16(gyro_y, 8u, 0xffu);
    gyro_z = (uint16_t)src_p->gyro_z;
    dst_p[17] |= pack_left_shift_u16(gyro_z, 0u, 0xffu);
    dst_p[18] |= pack_right_shift_u16(gyro_z, 8u, 0xffu);
    mag_x = (uint16_t)src_p->mag_x;
    dst_p[19] |= pack_left_shift_u16(mag_x, 0u, 0xffu);
    dst_p[20] |= pack_right_shift_u16(mag_x, 8u, 0xffu);
    mag_y = (uint16_t)src_p->mag_y;
    dst_p[21] |= pack_left_shift_u16(mag_y, 0u, 0xffu);
    dst_p[22] |= pack_right_shift_u16(mag_y, 8u, 0xffu);
    mag_z = (uint16_t)src_p->mag_z;
    dst_p[23] |= pack_left_shift_u16(mag_z, 0u, 0xffu);
    dst_p[24] |= pack_right_shift_u16(mag_z, 8u, 0xffu);

    return (26);
}

int roxy_front_daq_unpack(
    struct roxy_front_daq_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;
    uint16_t gyro_x;
    uint16_t gyro_y;
    uint16_t gyro_z;
    uint16_t mag_x;
    uint16_t mag_y;
    uint16_t mag_z;

    if (size < 26u) {
        return (-EINVAL);
    }

    dst_p->steering_angle = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->steering_angle |= unpack_left_shift_u16(src_p[1], 8u, 0x0fu);
    dst_p->brake_f = unpack_right_shift_u8(src_p[1], 4u, 0xf0u);
    dst_p->brake_f |= unpack_left_shift_u8(src_p[2], 4u, 0x0fu);
    dst_p->brake_r = unpack_right_shift_u8(src_p[2], 4u, 0xf0u);
    dst_p->brake_r |= unpack_left_shift_u8(src_p[3], 4u, 0x0fu);
    dst_p->linpot_r = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->linpot_r |= unpack_left_shift_u16(src_p[5], 8u, 0x0fu);
    dst_p->linpot_l = unpack_right_shift_u16(src_p[5], 4u, 0xf0u);
    dst_p->linpot_l |= unpack_left_shift_u16(src_p[6], 4u, 0xffu);
    accel_x = unpack_right_shift_u16(src_p[7], 0u, 0xffu);
    accel_x |= unpack_left_shift_u16(src_p[8], 8u, 0xffu);
    dst_p->accel_x = (int16_t)accel_x;
    accel_y = unpack_right_shift_u16(src_p[9], 0u, 0xffu);
    accel_y |= unpack_left_shift_u16(src_p[10], 8u, 0xffu);
    dst_p->accel_y = (int16_t)accel_y;
    accel_z = unpack_right_shift_u16(src_p[11], 0u, 0xffu);
    accel_z |= unpack_left_shift_u16(src_p[12], 8u, 0xffu);
    dst_p->accel_z = (int16_t)accel_z;
    gyro_x = unpack_right_shift_u16(src_p[13], 0u, 0xffu);
    gyro_x |= unpack_left_shift_u16(src_p[14], 8u, 0xffu);
    dst_p->gyro_x = (int16_t)gyro_x;
    gyro_y = unpack_right_shift_u16(src_p[15], 0u, 0xffu);
    gyro_y |= unpack_left_shift_u16(src_p[16], 8u, 0xffu);
    dst_p->gyro_y = (int16_t)gyro_y;
    gyro_z = unpack_right_shift_u16(src_p[17], 0u, 0xffu);
    gyro_z |= unpack_left_shift_u16(src_p[18], 8u, 0xffu);
    dst_p->gyro_z = (int16_t)gyro_z;
    mag_x = unpack_right_shift_u16(src_p[19], 0u, 0xffu);
    mag_x |= unpack_left_shift_u16(src_p[20], 8u, 0xffu);
    dst_p->mag_x = (int16_t)mag_x;
    mag_y = unpack_right_shift_u16(src_p[21], 0u, 0xffu);
    mag_y |= unpack_left_shift_u16(src_p[22], 8u, 0xffu);
    dst_p->mag_y = (int16_t)mag_y;
    mag_z = unpack_right_shift_u16(src_p[23], 0u, 0xffu);
    mag_z |= unpack_left_shift_u16(src_p[24], 8u, 0xffu);
    dst_p->mag_z = (int16_t)mag_z;

    return (0);
}

int roxy_front_daq_init(struct roxy_front_daq_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct roxy_front_daq_t));

    return 0;
}

uint16_t roxy_front_daq_steering_angle_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double roxy_front_daq_steering_angle_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool roxy_front_daq_steering_angle_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint8_t roxy_front_daq_brake_f_encode(double value)
{
    return (uint8_t)(value / 10.0);
}

double roxy_front_daq_brake_f_decode(uint8_t value)
{
    return ((double)value * 10.0);
}

bool roxy_front_daq_brake_f_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t roxy_front_daq_brake_r_encode(double value)
{
    return (uint8_t)(value);
}

double roxy_front_daq_brake_r_decode(uint8_t value)
{
    return ((double)value);
}

bool roxy_front_daq_brake_r_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t roxy_front_daq_linpot_r_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double roxy_front_daq_linpot_r_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool roxy_front_daq_linpot_r_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t roxy_front_daq_linpot_l_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double roxy_front_daq_linpot_l_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool roxy_front_daq_linpot_l_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

int16_t roxy_front_daq_accel_x_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double roxy_front_daq_accel_x_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool roxy_front_daq_accel_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t roxy_front_daq_accel_y_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double roxy_front_daq_accel_y_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool roxy_front_daq_accel_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t roxy_front_daq_accel_z_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double roxy_front_daq_accel_z_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool roxy_front_daq_accel_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t roxy_front_daq_gyro_x_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double roxy_front_daq_gyro_x_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool roxy_front_daq_gyro_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t roxy_front_daq_gyro_y_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double roxy_front_daq_gyro_y_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool roxy_front_daq_gyro_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t roxy_front_daq_gyro_z_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double roxy_front_daq_gyro_z_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool roxy_front_daq_gyro_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t roxy_front_daq_mag_x_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double roxy_front_daq_mag_x_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool roxy_front_daq_mag_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t roxy_front_daq_mag_y_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double roxy_front_daq_mag_y_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool roxy_front_daq_mag_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t roxy_front_daq_mag_z_encode(double value)
{
    return (int16_t)(value / 0.001);
}

double roxy_front_daq_mag_z_decode(int16_t value)
{
    return ((double)value * 0.001);
}

bool roxy_front_daq_mag_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}
