/**
 * @file roxy.h
 *
 * @brief This header file was generated by cantools version 40.7.1 Wed Sep 30 13:45:09 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef ROXY_H
#define ROXY_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define ROXY_REAR_DAQ_FRAME_ID (0x200u)
#define ROXY_FRONT_DAQ_FRAME_ID (0x300u)

/* Frame lengths in bytes. */
#define ROXY_REAR_DAQ_LENGTH (26u)
#define ROXY_FRONT_DAQ_LENGTH (26u)

/* Extended or standard frame types. */
#define ROXY_REAR_DAQ_IS_EXTENDED (0)
#define ROXY_FRONT_DAQ_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/* Frame Names. */
#define ROXY_REAR_DAQ_NAME "rear_daq"
#define ROXY_FRONT_DAQ_NAME "front_daq"

/* Signal Names. */
#define ROXY_REAR_DAQ_SPEEDOMETER_NAME "speedometer"
#define ROXY_REAR_DAQ_TACHOMETER_NAME "tachometer"
#define ROXY_REAR_DAQ_CVT_TEMP_NAME "cvt_temp"
#define ROXY_REAR_DAQ_AMBIENT_TEMP_NAME "ambient_temp"
#define ROXY_REAR_DAQ_LINPOT_R_NAME "linpot_r"
#define ROXY_REAR_DAQ_LINPOT_L_NAME "linpot_l"
#define ROXY_REAR_DAQ_ACCEL_X_NAME "accel_x"
#define ROXY_REAR_DAQ_ACCEL_Y_NAME "accel_y"
#define ROXY_REAR_DAQ_ACCEL_Z_NAME "accel_z"
#define ROXY_REAR_DAQ_GYRO_X_NAME "gyro_x"
#define ROXY_REAR_DAQ_GYRO_Y_NAME "gyro_y"
#define ROXY_REAR_DAQ_GYRO_Z_NAME "gyro_z"
#define ROXY_REAR_DAQ_MAG_X_NAME "mag_x"
#define ROXY_REAR_DAQ_MAG_Y_NAME "mag_y"
#define ROXY_REAR_DAQ_MAG_Z_NAME "mag_z"
#define ROXY_FRONT_DAQ_STEERING_ANGLE_NAME "steering_angle"
#define ROXY_FRONT_DAQ_BRAKE_F_NAME "brake_f"
#define ROXY_FRONT_DAQ_BRAKE_R_NAME "brake_r"
#define ROXY_FRONT_DAQ_LINPOT_R_NAME "linpot_r"
#define ROXY_FRONT_DAQ_LINPOT_L_NAME "linpot_l"
#define ROXY_FRONT_DAQ_ACCEL_X_NAME "accel_x"
#define ROXY_FRONT_DAQ_ACCEL_Y_NAME "accel_y"
#define ROXY_FRONT_DAQ_ACCEL_Z_NAME "accel_z"
#define ROXY_FRONT_DAQ_GYRO_X_NAME "gyro_x"
#define ROXY_FRONT_DAQ_GYRO_Y_NAME "gyro_y"
#define ROXY_FRONT_DAQ_GYRO_Z_NAME "gyro_z"
#define ROXY_FRONT_DAQ_MAG_X_NAME "mag_x"
#define ROXY_FRONT_DAQ_MAG_Y_NAME "mag_y"
#define ROXY_FRONT_DAQ_MAG_Z_NAME "mag_z"

/**
 * Signals in message rear_daq.
 *
 * All signal values are as on the CAN bus.
 */
struct roxy_rear_daq_t {
    /**
     * Range: 0..63 (0..63 km/h)
     * Scale: 1
     * Offset: 0
     */
    uint8_t speedometer;

    /**
     * Range: 0..4095 (0..4095 rpm)
     * Scale: 1
     * Offset: 0
     */
    uint16_t tachometer;

    /**
     * Range: 0..127 (0..127 celsius)
     * Scale: 1
     * Offset: 0
     */
    uint8_t cvt_temp;

    /**
     * Range: 0..127 (0..127 celsius)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ambient_temp;

    /**
     * Range: 0..4095 (0..40.95 cm)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t linpot_r;

    /**
     * Range: 0..4095 (0..40.95 cm)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t linpot_l;

    /**
     * Range: -32768..32767 (-32.768..32.767 -)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t accel_x;

    /**
     * Range: -32768..32767 (-32.768..32.767 -)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t accel_y;

    /**
     * Range: -32768..32767 (-32.768..32.767 -)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t accel_z;

    /**
     * Range: -32768..32767 (-32.768..32.767 -)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t gyro_x;

    /**
     * Range: -32768..32767 (-32.768..32.767 -)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t gyro_y;

    /**
     * Range: -32768..32767 (-32.768..32.767 -)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t gyro_z;

    /**
     * Range: -32768..32767 (-32.768..32.767 -)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t mag_x;

    /**
     * Range: -32768..32767 (-32.768..32.767 -)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t mag_y;

    /**
     * Range: -32768..32767 (-32.768..32.767 -)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t mag_z;
};

/**
 * Signals in message front_daq.
 *
 * All signal values are as on the CAN bus.
 */
struct roxy_front_daq_t {
    /**
     * Range: 0..4095 (0..409.5 -)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t steering_angle;

    /**
     * Range: 0..255 (0..2550 -)
     * Scale: 10
     * Offset: 0
     */
    uint8_t brake_f;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t brake_r;

    /**
     * Range: 0..4095 (0..40.95 cm)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t linpot_r;

    /**
     * Range: 0..4095 (0..40.95 cm)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t linpot_l;

    /**
     * Range: -32768..32767 (-32.768..32.767 -)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t accel_x;

    /**
     * Range: -32768..32767 (-32.768..32.767 -)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t accel_y;

    /**
     * Range: -32768..32767 (-32.768..32.767 -)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t accel_z;

    /**
     * Range: -32768..32767 (-32.768..32.767 -)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t gyro_x;

    /**
     * Range: -32768..32767 (-32.768..32.767 -)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t gyro_y;

    /**
     * Range: -32768..32767 (-32.768..32.767 -)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t gyro_z;

    /**
     * Range: -32768..32767 (-32.768..32.767 -)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t mag_x;

    /**
     * Range: -32768..32767 (-32.768..32.767 -)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t mag_y;

    /**
     * Range: -32768..32767 (-32.768..32.767 -)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t mag_z;
};

/**
 * Pack message rear_daq.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int roxy_rear_daq_pack(
    uint8_t *dst_p,
    const struct roxy_rear_daq_t *src_p,
    size_t size);

/**
 * Unpack message rear_daq.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int roxy_rear_daq_unpack(
    struct roxy_rear_daq_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from rear_daq.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int roxy_rear_daq_init(struct roxy_rear_daq_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t roxy_rear_daq_speedometer_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_rear_daq_speedometer_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_rear_daq_speedometer_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t roxy_rear_daq_tachometer_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_rear_daq_tachometer_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_rear_daq_tachometer_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t roxy_rear_daq_cvt_temp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_rear_daq_cvt_temp_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_rear_daq_cvt_temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t roxy_rear_daq_ambient_temp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_rear_daq_ambient_temp_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_rear_daq_ambient_temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t roxy_rear_daq_linpot_r_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_rear_daq_linpot_r_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_rear_daq_linpot_r_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t roxy_rear_daq_linpot_l_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_rear_daq_linpot_l_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_rear_daq_linpot_l_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t roxy_rear_daq_accel_x_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_rear_daq_accel_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_rear_daq_accel_x_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t roxy_rear_daq_accel_y_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_rear_daq_accel_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_rear_daq_accel_y_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t roxy_rear_daq_accel_z_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_rear_daq_accel_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_rear_daq_accel_z_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t roxy_rear_daq_gyro_x_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_rear_daq_gyro_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_rear_daq_gyro_x_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t roxy_rear_daq_gyro_y_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_rear_daq_gyro_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_rear_daq_gyro_y_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t roxy_rear_daq_gyro_z_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_rear_daq_gyro_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_rear_daq_gyro_z_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t roxy_rear_daq_mag_x_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_rear_daq_mag_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_rear_daq_mag_x_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t roxy_rear_daq_mag_y_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_rear_daq_mag_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_rear_daq_mag_y_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t roxy_rear_daq_mag_z_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_rear_daq_mag_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_rear_daq_mag_z_is_in_range(int16_t value);

/**
 * Pack message front_daq.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int roxy_front_daq_pack(
    uint8_t *dst_p,
    const struct roxy_front_daq_t *src_p,
    size_t size);

/**
 * Unpack message front_daq.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int roxy_front_daq_unpack(
    struct roxy_front_daq_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from front_daq.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int roxy_front_daq_init(struct roxy_front_daq_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t roxy_front_daq_steering_angle_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_front_daq_steering_angle_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_front_daq_steering_angle_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t roxy_front_daq_brake_f_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_front_daq_brake_f_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_front_daq_brake_f_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t roxy_front_daq_brake_r_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_front_daq_brake_r_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_front_daq_brake_r_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t roxy_front_daq_linpot_r_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_front_daq_linpot_r_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_front_daq_linpot_r_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t roxy_front_daq_linpot_l_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_front_daq_linpot_l_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_front_daq_linpot_l_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t roxy_front_daq_accel_x_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_front_daq_accel_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_front_daq_accel_x_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t roxy_front_daq_accel_y_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_front_daq_accel_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_front_daq_accel_y_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t roxy_front_daq_accel_z_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_front_daq_accel_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_front_daq_accel_z_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t roxy_front_daq_gyro_x_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_front_daq_gyro_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_front_daq_gyro_x_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t roxy_front_daq_gyro_y_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_front_daq_gyro_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_front_daq_gyro_y_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t roxy_front_daq_gyro_z_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_front_daq_gyro_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_front_daq_gyro_z_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t roxy_front_daq_mag_x_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_front_daq_mag_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_front_daq_mag_x_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t roxy_front_daq_mag_y_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_front_daq_mag_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_front_daq_mag_y_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t roxy_front_daq_mag_z_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double roxy_front_daq_mag_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool roxy_front_daq_mag_z_is_in_range(int16_t value);


#ifdef __cplusplus
}
#endif

#endif
