/**
 * @file mochi.c
 *
 * @brief This source file was generated by cantools version 41.4.3 Mon Jun 22 13:03:22 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "mochi.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int mochi_rr_imu_pack(
    uint8_t *dst_p,
    const struct mochi_rr_imu_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;
    uint16_t gyro_x;
    uint16_t gyro_y;
    uint16_t gyro_z;

    if (size < 12u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 12);

    accel_x = (uint16_t)src_p->accel_x;
    dst_p[0] |= pack_left_shift_u16(accel_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(accel_x, 8u, 0xffu);
    accel_y = (uint16_t)src_p->accel_y;
    dst_p[2] |= pack_left_shift_u16(accel_y, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(accel_y, 8u, 0xffu);
    accel_z = (uint16_t)src_p->accel_z;
    dst_p[4] |= pack_left_shift_u16(accel_z, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(accel_z, 8u, 0xffu);
    gyro_x = (uint16_t)src_p->gyro_x;
    dst_p[6] |= pack_left_shift_u16(gyro_x, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(gyro_x, 8u, 0xffu);
    gyro_y = (uint16_t)src_p->gyro_y;
    dst_p[8] |= pack_left_shift_u16(gyro_y, 0u, 0xffu);
    dst_p[9] |= pack_right_shift_u16(gyro_y, 8u, 0xffu);
    gyro_z = (uint16_t)src_p->gyro_z;
    dst_p[10] |= pack_left_shift_u16(gyro_z, 0u, 0xffu);
    dst_p[11] |= pack_right_shift_u16(gyro_z, 8u, 0xffu);

    return (12);
}

int mochi_rr_imu_unpack(
    struct mochi_rr_imu_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;
    uint16_t gyro_x;
    uint16_t gyro_y;
    uint16_t gyro_z;

    if (size < 12u) {
        return (-EINVAL);
    }

    accel_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    accel_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->accel_x = (int16_t)accel_x;
    accel_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    accel_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->accel_y = (int16_t)accel_y;
    accel_z = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    accel_z |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->accel_z = (int16_t)accel_z;
    gyro_x = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    gyro_x |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->gyro_x = (int16_t)gyro_x;
    gyro_y = unpack_right_shift_u16(src_p[8], 0u, 0xffu);
    gyro_y |= unpack_left_shift_u16(src_p[9], 8u, 0xffu);
    dst_p->gyro_y = (int16_t)gyro_y;
    gyro_z = unpack_right_shift_u16(src_p[10], 0u, 0xffu);
    gyro_z |= unpack_left_shift_u16(src_p[11], 8u, 0xffu);
    dst_p->gyro_z = (int16_t)gyro_z;

    return (0);
}

int mochi_rr_imu_init(struct mochi_rr_imu_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mochi_rr_imu_t));

    return 0;
}

int16_t mochi_rr_imu_accel_x_encode(double value)
{
    return (int16_t)(value);
}

double mochi_rr_imu_accel_x_decode(int16_t value)
{
    return ((double)value);
}

bool mochi_rr_imu_accel_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool mochi_rr_imu_accel_x_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int16_t mochi_rr_imu_accel_y_encode(double value)
{
    return (int16_t)(value);
}

double mochi_rr_imu_accel_y_decode(int16_t value)
{
    return ((double)value);
}

bool mochi_rr_imu_accel_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool mochi_rr_imu_accel_y_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int16_t mochi_rr_imu_accel_z_encode(double value)
{
    return (int16_t)(value);
}

double mochi_rr_imu_accel_z_decode(int16_t value)
{
    return ((double)value);
}

bool mochi_rr_imu_accel_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool mochi_rr_imu_accel_z_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int16_t mochi_rr_imu_gyro_x_encode(double value)
{
    return (int16_t)(value);
}

double mochi_rr_imu_gyro_x_decode(int16_t value)
{
    return ((double)value);
}

bool mochi_rr_imu_gyro_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool mochi_rr_imu_gyro_x_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int16_t mochi_rr_imu_gyro_y_encode(double value)
{
    return (int16_t)(value);
}

double mochi_rr_imu_gyro_y_decode(int16_t value)
{
    return ((double)value);
}

bool mochi_rr_imu_gyro_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool mochi_rr_imu_gyro_y_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int16_t mochi_rr_imu_gyro_z_encode(double value)
{
    return (int16_t)(value);
}

double mochi_rr_imu_gyro_z_decode(int16_t value)
{
    return ((double)value);
}

bool mochi_rr_imu_gyro_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool mochi_rr_imu_gyro_z_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int mochi_rr_suspension_pack(
    uint8_t *dst_p,
    const struct mochi_rr_suspension_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->travel, 0u, 0xffu);

    return (1);
}

int mochi_rr_suspension_unpack(
    struct mochi_rr_suspension_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->travel = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int mochi_rr_suspension_init(struct mochi_rr_suspension_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mochi_rr_suspension_t));

    return 0;
}

uint8_t mochi_rr_suspension_travel_encode(double value)
{
    return (uint8_t)(value);
}

double mochi_rr_suspension_travel_decode(uint8_t value)
{
    return ((double)value);
}

bool mochi_rr_suspension_travel_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool mochi_rr_suspension_travel_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int mochi_rl_imu_pack(
    uint8_t *dst_p,
    const struct mochi_rl_imu_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;
    uint16_t gyro_x;
    uint16_t gyro_y;
    uint16_t gyro_z;

    if (size < 12u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 12);

    accel_x = (uint16_t)src_p->accel_x;
    dst_p[0] |= pack_left_shift_u16(accel_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(accel_x, 8u, 0xffu);
    accel_y = (uint16_t)src_p->accel_y;
    dst_p[2] |= pack_left_shift_u16(accel_y, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(accel_y, 8u, 0xffu);
    accel_z = (uint16_t)src_p->accel_z;
    dst_p[4] |= pack_left_shift_u16(accel_z, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(accel_z, 8u, 0xffu);
    gyro_x = (uint16_t)src_p->gyro_x;
    dst_p[6] |= pack_left_shift_u16(gyro_x, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(gyro_x, 8u, 0xffu);
    gyro_y = (uint16_t)src_p->gyro_y;
    dst_p[8] |= pack_left_shift_u16(gyro_y, 0u, 0xffu);
    dst_p[9] |= pack_right_shift_u16(gyro_y, 8u, 0xffu);
    gyro_z = (uint16_t)src_p->gyro_z;
    dst_p[10] |= pack_left_shift_u16(gyro_z, 0u, 0xffu);
    dst_p[11] |= pack_right_shift_u16(gyro_z, 8u, 0xffu);

    return (12);
}

int mochi_rl_imu_unpack(
    struct mochi_rl_imu_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;
    uint16_t gyro_x;
    uint16_t gyro_y;
    uint16_t gyro_z;

    if (size < 12u) {
        return (-EINVAL);
    }

    accel_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    accel_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->accel_x = (int16_t)accel_x;
    accel_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    accel_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->accel_y = (int16_t)accel_y;
    accel_z = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    accel_z |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->accel_z = (int16_t)accel_z;
    gyro_x = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    gyro_x |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->gyro_x = (int16_t)gyro_x;
    gyro_y = unpack_right_shift_u16(src_p[8], 0u, 0xffu);
    gyro_y |= unpack_left_shift_u16(src_p[9], 8u, 0xffu);
    dst_p->gyro_y = (int16_t)gyro_y;
    gyro_z = unpack_right_shift_u16(src_p[10], 0u, 0xffu);
    gyro_z |= unpack_left_shift_u16(src_p[11], 8u, 0xffu);
    dst_p->gyro_z = (int16_t)gyro_z;

    return (0);
}

int mochi_rl_imu_init(struct mochi_rl_imu_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mochi_rl_imu_t));

    return 0;
}

int16_t mochi_rl_imu_accel_x_encode(double value)
{
    return (int16_t)(value);
}

double mochi_rl_imu_accel_x_decode(int16_t value)
{
    return ((double)value);
}

bool mochi_rl_imu_accel_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool mochi_rl_imu_accel_x_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int16_t mochi_rl_imu_accel_y_encode(double value)
{
    return (int16_t)(value);
}

double mochi_rl_imu_accel_y_decode(int16_t value)
{
    return ((double)value);
}

bool mochi_rl_imu_accel_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool mochi_rl_imu_accel_y_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int16_t mochi_rl_imu_accel_z_encode(double value)
{
    return (int16_t)(value);
}

double mochi_rl_imu_accel_z_decode(int16_t value)
{
    return ((double)value);
}

bool mochi_rl_imu_accel_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool mochi_rl_imu_accel_z_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int16_t mochi_rl_imu_gyro_x_encode(double value)
{
    return (int16_t)(value);
}

double mochi_rl_imu_gyro_x_decode(int16_t value)
{
    return ((double)value);
}

bool mochi_rl_imu_gyro_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool mochi_rl_imu_gyro_x_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int16_t mochi_rl_imu_gyro_y_encode(double value)
{
    return (int16_t)(value);
}

double mochi_rl_imu_gyro_y_decode(int16_t value)
{
    return ((double)value);
}

bool mochi_rl_imu_gyro_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool mochi_rl_imu_gyro_y_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int16_t mochi_rl_imu_gyro_z_encode(double value)
{
    return (int16_t)(value);
}

double mochi_rl_imu_gyro_z_decode(int16_t value)
{
    return ((double)value);
}

bool mochi_rl_imu_gyro_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool mochi_rl_imu_gyro_z_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int mochi_rl_suspension_pack(
    uint8_t *dst_p,
    const struct mochi_rl_suspension_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->travel, 0u, 0xffu);

    return (1);
}

int mochi_rl_suspension_unpack(
    struct mochi_rl_suspension_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->travel = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int mochi_rl_suspension_init(struct mochi_rl_suspension_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mochi_rl_suspension_t));

    return 0;
}

uint8_t mochi_rl_suspension_travel_encode(double value)
{
    return (uint8_t)(value);
}

double mochi_rl_suspension_travel_decode(uint8_t value)
{
    return ((double)value);
}

bool mochi_rl_suspension_travel_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool mochi_rl_suspension_travel_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int mochi_fr_imu_pack(
    uint8_t *dst_p,
    const struct mochi_fr_imu_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;
    uint16_t gyro_x;
    uint16_t gyro_y;
    uint16_t gyro_z;

    if (size < 12u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 12);

    accel_x = (uint16_t)src_p->accel_x;
    dst_p[0] |= pack_left_shift_u16(accel_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(accel_x, 8u, 0xffu);
    accel_y = (uint16_t)src_p->accel_y;
    dst_p[2] |= pack_left_shift_u16(accel_y, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(accel_y, 8u, 0xffu);
    accel_z = (uint16_t)src_p->accel_z;
    dst_p[4] |= pack_left_shift_u16(accel_z, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(accel_z, 8u, 0xffu);
    gyro_x = (uint16_t)src_p->gyro_x;
    dst_p[6] |= pack_left_shift_u16(gyro_x, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(gyro_x, 8u, 0xffu);
    gyro_y = (uint16_t)src_p->gyro_y;
    dst_p[8] |= pack_left_shift_u16(gyro_y, 0u, 0xffu);
    dst_p[9] |= pack_right_shift_u16(gyro_y, 8u, 0xffu);
    gyro_z = (uint16_t)src_p->gyro_z;
    dst_p[10] |= pack_left_shift_u16(gyro_z, 0u, 0xffu);
    dst_p[11] |= pack_right_shift_u16(gyro_z, 8u, 0xffu);

    return (12);
}

int mochi_fr_imu_unpack(
    struct mochi_fr_imu_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;
    uint16_t gyro_x;
    uint16_t gyro_y;
    uint16_t gyro_z;

    if (size < 12u) {
        return (-EINVAL);
    }

    accel_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    accel_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->accel_x = (int16_t)accel_x;
    accel_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    accel_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->accel_y = (int16_t)accel_y;
    accel_z = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    accel_z |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->accel_z = (int16_t)accel_z;
    gyro_x = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    gyro_x |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->gyro_x = (int16_t)gyro_x;
    gyro_y = unpack_right_shift_u16(src_p[8], 0u, 0xffu);
    gyro_y |= unpack_left_shift_u16(src_p[9], 8u, 0xffu);
    dst_p->gyro_y = (int16_t)gyro_y;
    gyro_z = unpack_right_shift_u16(src_p[10], 0u, 0xffu);
    gyro_z |= unpack_left_shift_u16(src_p[11], 8u, 0xffu);
    dst_p->gyro_z = (int16_t)gyro_z;

    return (0);
}

int mochi_fr_imu_init(struct mochi_fr_imu_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mochi_fr_imu_t));

    return 0;
}

int16_t mochi_fr_imu_accel_x_encode(double value)
{
    return (int16_t)(value);
}

double mochi_fr_imu_accel_x_decode(int16_t value)
{
    return ((double)value);
}

bool mochi_fr_imu_accel_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool mochi_fr_imu_accel_x_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int16_t mochi_fr_imu_accel_y_encode(double value)
{
    return (int16_t)(value);
}

double mochi_fr_imu_accel_y_decode(int16_t value)
{
    return ((double)value);
}

bool mochi_fr_imu_accel_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool mochi_fr_imu_accel_y_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int16_t mochi_fr_imu_accel_z_encode(double value)
{
    return (int16_t)(value);
}

double mochi_fr_imu_accel_z_decode(int16_t value)
{
    return ((double)value);
}

bool mochi_fr_imu_accel_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool mochi_fr_imu_accel_z_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int16_t mochi_fr_imu_gyro_x_encode(double value)
{
    return (int16_t)(value);
}

double mochi_fr_imu_gyro_x_decode(int16_t value)
{
    return ((double)value);
}

bool mochi_fr_imu_gyro_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool mochi_fr_imu_gyro_x_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int16_t mochi_fr_imu_gyro_y_encode(double value)
{
    return (int16_t)(value);
}

double mochi_fr_imu_gyro_y_decode(int16_t value)
{
    return ((double)value);
}

bool mochi_fr_imu_gyro_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool mochi_fr_imu_gyro_y_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int16_t mochi_fr_imu_gyro_z_encode(double value)
{
    return (int16_t)(value);
}

double mochi_fr_imu_gyro_z_decode(int16_t value)
{
    return ((double)value);
}

bool mochi_fr_imu_gyro_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool mochi_fr_imu_gyro_z_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int mochi_fr_suspension_pack(
    uint8_t *dst_p,
    const struct mochi_fr_suspension_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->travel, 0u, 0xffu);

    return (1);
}

int mochi_fr_suspension_unpack(
    struct mochi_fr_suspension_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->travel = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int mochi_fr_suspension_init(struct mochi_fr_suspension_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mochi_fr_suspension_t));

    return 0;
}

uint8_t mochi_fr_suspension_travel_encode(double value)
{
    return (uint8_t)(value);
}

double mochi_fr_suspension_travel_decode(uint8_t value)
{
    return ((double)value);
}

bool mochi_fr_suspension_travel_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool mochi_fr_suspension_travel_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int mochi_fl_imu_pack(
    uint8_t *dst_p,
    const struct mochi_fl_imu_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;
    uint16_t gyro_x;
    uint16_t gyro_y;
    uint16_t gyro_z;

    if (size < 12u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 12);

    accel_x = (uint16_t)src_p->accel_x;
    dst_p[0] |= pack_left_shift_u16(accel_x, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(accel_x, 8u, 0xffu);
    accel_y = (uint16_t)src_p->accel_y;
    dst_p[2] |= pack_left_shift_u16(accel_y, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(accel_y, 8u, 0xffu);
    accel_z = (uint16_t)src_p->accel_z;
    dst_p[4] |= pack_left_shift_u16(accel_z, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(accel_z, 8u, 0xffu);
    gyro_x = (uint16_t)src_p->gyro_x;
    dst_p[6] |= pack_left_shift_u16(gyro_x, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(gyro_x, 8u, 0xffu);
    gyro_y = (uint16_t)src_p->gyro_y;
    dst_p[8] |= pack_left_shift_u16(gyro_y, 0u, 0xffu);
    dst_p[9] |= pack_right_shift_u16(gyro_y, 8u, 0xffu);
    gyro_z = (uint16_t)src_p->gyro_z;
    dst_p[10] |= pack_left_shift_u16(gyro_z, 0u, 0xffu);
    dst_p[11] |= pack_right_shift_u16(gyro_z, 8u, 0xffu);

    return (12);
}

int mochi_fl_imu_unpack(
    struct mochi_fl_imu_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;
    uint16_t gyro_x;
    uint16_t gyro_y;
    uint16_t gyro_z;

    if (size < 12u) {
        return (-EINVAL);
    }

    accel_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    accel_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->accel_x = (int16_t)accel_x;
    accel_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    accel_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->accel_y = (int16_t)accel_y;
    accel_z = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    accel_z |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->accel_z = (int16_t)accel_z;
    gyro_x = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    gyro_x |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->gyro_x = (int16_t)gyro_x;
    gyro_y = unpack_right_shift_u16(src_p[8], 0u, 0xffu);
    gyro_y |= unpack_left_shift_u16(src_p[9], 8u, 0xffu);
    dst_p->gyro_y = (int16_t)gyro_y;
    gyro_z = unpack_right_shift_u16(src_p[10], 0u, 0xffu);
    gyro_z |= unpack_left_shift_u16(src_p[11], 8u, 0xffu);
    dst_p->gyro_z = (int16_t)gyro_z;

    return (0);
}

int mochi_fl_imu_init(struct mochi_fl_imu_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mochi_fl_imu_t));

    return 0;
}

int16_t mochi_fl_imu_accel_x_encode(double value)
{
    return (int16_t)(value);
}

double mochi_fl_imu_accel_x_decode(int16_t value)
{
    return ((double)value);
}

bool mochi_fl_imu_accel_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool mochi_fl_imu_accel_x_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int16_t mochi_fl_imu_accel_y_encode(double value)
{
    return (int16_t)(value);
}

double mochi_fl_imu_accel_y_decode(int16_t value)
{
    return ((double)value);
}

bool mochi_fl_imu_accel_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool mochi_fl_imu_accel_y_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int16_t mochi_fl_imu_accel_z_encode(double value)
{
    return (int16_t)(value);
}

double mochi_fl_imu_accel_z_decode(int16_t value)
{
    return ((double)value);
}

bool mochi_fl_imu_accel_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool mochi_fl_imu_accel_z_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int16_t mochi_fl_imu_gyro_x_encode(double value)
{
    return (int16_t)(value);
}

double mochi_fl_imu_gyro_x_decode(int16_t value)
{
    return ((double)value);
}

bool mochi_fl_imu_gyro_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool mochi_fl_imu_gyro_x_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int16_t mochi_fl_imu_gyro_y_encode(double value)
{
    return (int16_t)(value);
}

double mochi_fl_imu_gyro_y_decode(int16_t value)
{
    return ((double)value);
}

bool mochi_fl_imu_gyro_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool mochi_fl_imu_gyro_y_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int16_t mochi_fl_imu_gyro_z_encode(double value)
{
    return (int16_t)(value);
}

double mochi_fl_imu_gyro_z_decode(int16_t value)
{
    return ((double)value);
}

bool mochi_fl_imu_gyro_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool mochi_fl_imu_gyro_z_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int mochi_fl_suspension_pack(
    uint8_t *dst_p,
    const struct mochi_fl_suspension_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->travel, 0u, 0xffu);

    return (1);
}

int mochi_fl_suspension_unpack(
    struct mochi_fl_suspension_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->travel = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int mochi_fl_suspension_init(struct mochi_fl_suspension_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mochi_fl_suspension_t));

    return 0;
}

uint8_t mochi_fl_suspension_travel_encode(double value)
{
    return (uint8_t)(value);
}

double mochi_fl_suspension_travel_decode(uint8_t value)
{
    return ((double)value);
}

bool mochi_fl_suspension_travel_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool mochi_fl_suspension_travel_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int mochi_rear_ecu_status_pack(
    uint8_t *dst_p,
    const struct mochi_rear_ecu_status_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u16(src_p->speedometer, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->speedometer, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->tachometer, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->tachometer, 8u, 0xffu);

    return (4);
}

int mochi_rear_ecu_status_unpack(
    struct mochi_rear_ecu_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->speedometer = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->speedometer |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->tachometer = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->tachometer |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);

    return (0);
}

int mochi_rear_ecu_status_init(struct mochi_rear_ecu_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct mochi_rear_ecu_status_t));

    return 0;
}

uint16_t mochi_rear_ecu_status_speedometer_encode(double value)
{
    return (uint16_t)(value);
}

double mochi_rear_ecu_status_speedometer_decode(uint16_t value)
{
    return ((double)value);
}

bool mochi_rear_ecu_status_speedometer_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool mochi_rear_ecu_status_speedometer_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 65535.0));
}

uint16_t mochi_rear_ecu_status_tachometer_encode(double value)
{
    return (uint16_t)(value);
}

double mochi_rear_ecu_status_tachometer_decode(uint16_t value)
{
    return ((double)value);
}

bool mochi_rear_ecu_status_tachometer_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool mochi_rear_ecu_status_tachometer_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 65535.0));
}
